### ISSUE TITLE
打扰一下

### ISSUE THREAD

**Issue by P7c0d32** [xzr467706992/android_kernel_oneplus_sm8250#4]
请问 baseline-r 分支是 能编译通过 能启动 的初始版本吗？

**Comment by libxzr** [comment]
不是 那是纯高通CAF代码合并linux stable

**Comment by P7c0d32** [comment]
> 不是 那是纯高通CAF代码合并linux stable

你好，我也是一个学生。我最近几天编译过各种 op8t sm8250 的代码，少说有个二十多次了，无一例外，总是报这条错：
```
CHK     kernel/kheaders_data.tar.xz
make[3]: *** No rule to make target 'arch/arm64/boot/dts/qcom/apq8016-sbc.dtb', needed by '__build'.  Stop.
make[3]: *** Waiting for unfinished jobs....
../scripts/Makefile.build:642: recipe for target 'arch/arm64/boot/dts/qcom' failed
make[2]: *** [arch/arm64/boot/dts/qcom] Error 2
arch/arm64/Makefile:172: recipe for target 'dtbs' failed
make[1]: *** [dtbs] Error 2
make[1]: *** Waiting for unfinished jobs....
```

但是我发现您的代码可以 **编译的很顺畅，而且启动和运行都正常，硬件都能正确驱动**。按照网友的方法，我 *注释过 Makefile 中 DTC 的相关部分*，虽然能编译通过，但是不能启动。我也看了很久您的 commit，也对比过其他仓库的，也对旧版本做过 diff，确实 *没有看懂* 是怎么解决这个问题的。XDA 上有个 [Handelinkernel ](https://github.com/OnePlusOSS/android_kernel_oneplus_sm8250)，我看到这个仓库引用过您的代码，但是我编译他的代码也是失败。

我做过的一些尝试：使用 `Snapdragon-LLVM-10.0.9`，使用 `aarch64-linux-android-4.9`，复制您的 `dtc-aosp` 和 `Makefile` 里的相关改动。

我所用的编译命令：
```bash
make O=out REAL_CC=/path/to/Snapdragon-LLVM-10.0.9/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- vendor/kona-perf_defconfig
make -j4 O=out REAL_CC=/path/to//Snapdragon-LLVM-10.0.9/bin/clang CLANG_TRIPLE=aarch64-linux-gnu-
```

总之，所以我很想知道，这个编译问题您当初 *是怎么解决的*。能指出当初的 commit 最好不过了，非常感谢。

**Comment by YumeMichi** [comment]
qcom目录的dts不需要
https://github.com/xzr467706992/android_kernel_oneplus_sm8250/commit/97fcc5830e0c70f5ca741462d09981fc6ce57dcb

**Comment by P7c0d32** [comment]
> qcom目录的dts不需要
> [97fcc58](https://github.com/xzr467706992/android_kernel_oneplus_sm8250/commit/97fcc5830e0c70f5ca741462d09981fc6ce57dcb)

谢谢，编译成功了
